# If named releases will delete the existing releases folder
# which contains manifests used at this action.
dist: releases-go

builds:
  - id: default
    main: ./cmd/core-controller
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
    goarm:
      - "7"

archives:
  - id: default
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge pull request"

release:

  header: |
    ## Installation

    Install all TriggerMesh Core custom resources:

    ```console
    kubectl apply -f https://github.com/triggermesh/triggermesh-core/releases/download/{{ .Tag }}/triggermesh-core-crds.yaml
    ```

    Install the TriggerMesh Core controller:

    ```console
    kubectl apply -f https://github.com/triggermesh/triggermesh-core/releases/download/{{ .Tag }}/triggermesh-core.yaml
    ```

  extra_files:
    - glob: ./releases/manifests/triggermesh-core.yaml
    - glob: ./releases/manifests/triggermesh-core-crds.yaml
