# kubectl -n tm apply -f https://raw.githubusercontent.com/triggermesh/triggermesh-core/main/docs/assets/manifests/getting-started-redis/broker.yaml
apiVersion: eventing.triggermesh.io/v1alpha1
kind: RedisReplay
metadata:
  name: example-redisreplay
spec:
  startTime: "2023-04-04T00:00:00Z"
  endTime: "2023-04-04T23:59:59Z"
  filters:
    - cesql: "type = 'com.example.event'"
