# Copyright 2022 TriggerMesh Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: triggermesh-core-controller
  labels:
    app.kubernetes.io/part-of: triggermesh

rules:

# Record Kubernetes events
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
  - update

# Manage broker deployments
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch

# Manage broker services, endpoints and secrets (for configuration)
- apiGroups:
  - ''
  resources:
  - services
  - endpoints
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch



# Read reconciled TriggerMesh core resources and update their statuses
# +rbac-check
- apiGroups:
  - eventing.triggermesh.io
  resources:
  - memorybrokers
  - redisbrokers
  - triggers
  verbs:
  - list
  - watch
  - get
# +rbac-check:subresource=status
- apiGroups:
  - eventing.triggermesh.io
  resources:
  - memorybrokers/status
  - redisbrokers/status
  - triggers/status
  verbs:
  - update

# Ensure compatibility with the OwnerReferencesPermissionEnforcement Admission Controller
# https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
# +rbac-check:subresource=finalizers
- apiGroups:
  - eventing.triggermesh.io
  resources:
  - memorybrokers/finalizers
  - redisbrokers/finalizers
  - triggers/finalizers
  verbs:
  - update

# Set finalizers
- apiGroups:
  - eventing.triggermesh.io
  resources:
  - memorybrokers
  - redisbrokers
  - triggers
  verbs:
  - patch

# Manage resource-specific ServiceAccounts and RoleBindings
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  - serviceaccounts/finalizers
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
  - watch
  - create

# Read configuration/credentials
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get

# Read controller configurations
# Create and read broker status ConfigMaps
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - create
  - get
- apiGroups:
  - ''
  resources:
  - configmaps
  resourceNames:
  - config-logging
  - config-observability
  - config-leader-election
  verbs:
  - get

# Acquire leases for leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: triggermesh-broker
  labels:
    app.kubernetes.io/part-of: triggermesh
rules:

# Read broker configuration, including credentials.
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - list
  - watch
  - get

# Read observability configuration.
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get
